### PR TITLE
Adding yarn, the prop-types package, and changed references to PropTypes

### PR DESCRIPTION
**Pull request by danyim**
React 15.6 started issuing warnings for packages that depended on `React.PropTypes` instead of using the `prop-types` package. This PR will address this issue and add a yarn lockfile to the repo.
 
```text
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
```

### CODE REVIEW

**Review by martpie — APPROVED** [review]
Looks good, thank you!

I will publish an update once I will get to my laptop.

**Comment by danyim** [comment]
@KeitIG Could you bump the version to `0.4.2` in package.json and run `npm publish`?

**Comment by martpie** [comment]
Done, sorry for the delay.

**Comment by danyim** [comment]
Awesome! Thanks for sharing this useful component!

**Pull request merged**
